version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/html
    volumes_from:
      - app
    ports:
      - 8080:80
    links:
      - mysql


  # The Database
#  database:
#    image: mysql:5.7
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=OOP"
#      - "MYSQL_USER=root"
#      - "MYSQL_PASSWORD=qwerty"
#      - "MYSQL_ROOT_PASSWORD=qwerty"
#    ports:
#        - "33061:3306"
#
#volumes:
#  dbdata:

  mysql:
      build: builds/mysql
      container_name: mysql
      ports:
        - 33061:3306
      environment:
        - MYSQL_ROOT_PASSWORD=qwerty
      volumes:
        - /Documents/workspace/php_Lynda_cursus/example.com/_mysql:/var/lib/mysql
